import { useEffect, useState, type ChangeEvent } from "react";
import axios from "axios";
import { Link, useNavigate, useParams } from "react-router-dom";
import { documentsApi, landRecordsApi, exportApi } from "@/services/api";
import { useAuth } from "@/hooks/useAuth";
import type { Document, ExtractionResult, LandRecord, PaginatedResponse } from "@/types";

const card = "bg-white border border-slate-200 rounded-xl p-5";
function ErrorBox({ message }: { message: string }) { return <div className="p-3 rounded-lg bg-red-50 text-red-700 text-sm">{message}</div>; }
function Empty({ text }: { text: string }) { return <div className="py-12 text-center text-slate-500">{text}</div>; }

export function UploadPage() {
  const [file, setFile] = useState<File | null>(null); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [busy, setBusy] = useState(false); const navigate = useNavigate();
  const choose = (e: ChangeEvent<HTMLInputElement>) => { const f = e.target.files?.[0]; if (f) validate(f); };
  const validate = (f: File) => { const problem = f.size > 20 * 1024 * 1024 ? "File exceeds the 20MB limit" : !/\.(pdf|png|jpg|jpeg|tif|tiff|webp)$/i.test(f.name) ? "Use a PDF or supported image file" : ""; setError(problem); if (!problem) setFile(f); };
  const upload = async () => { if (!file || error) return; setBusy(true); setError(""); setMessage(""); try { const { data } = await documentsApi.upload(file); setMessage("Uploaded. Starting processing…"); await documentsApi.process(data.id); navigate(`/documents/${data.id}`); } catch (caughtError) { setMessage(""); const detail = axios.isAxiosError(caughtError) ? caughtError.response?.data?.detail : null; setError(typeof detail === "string" ? detail : caughtError instanceof Error ? caughtError.message : "Upload or processing could not be started."); } finally { setBusy(false); } };
  return <div className="max-w-2xl"><h2 className="text-2xl font-bold mb-2">Upload land document</h2><p className="text-slate-500 mb-6">PDF, PNG, JPG, TIFF or WEBP · maximum 20MB</p><label className="block border-2 border-dashed border-slate-300 rounded-xl bg-white p-12 text-center cursor-pointer hover:border-blue-500"><input type="file" className="hidden" accept=".pdf,.png,.jpg,.jpeg,.tif,.tiff,.webp" onChange={choose}/><p className="font-medium">Drop a document here or choose a file</p><p className="text-sm text-slate-500 mt-2">Hindi and English documents are supported</p></label>{file && <div className={`${card} mt-4 flex justify-between`}><span>{file.name}</span><span className="text-slate-500">{(file.size / 1024 / 1024).toFixed(2)} MB</span></div>}{error && <div className="mt-4"><ErrorBox message={error}/></div>}{message && <p className="mt-4 text-green-700">{message}</p>}<button onClick={upload} disabled={!file || !!error || busy} className="mt-6 bg-blue-600 text-white px-5 py-2 rounded-lg disabled:opacity-50">{busy ? "Uploading…" : "Upload and process"}</button></div>;
}

export function DocumentsPage() { const [data, setData] = useState<PaginatedResponse<Document> | null>(null); const [error, setError] = useState(""); const [page, setPage] = useState(1); useEffect(() => { documentsApi.list({ page, page_size: 20 }).then(r => setData(r.data)).catch(() => setError("Failed to load documents")); }, [page]); return <div><h2 className="text-2xl font-bold mb-6">Documents</h2>{error && <ErrorBox message={error}/>} {!data ? <p>Loading…</p> : data.items.length === 0 ? <Empty text="No documents uploaded yet."/> : <><div className="overflow-x-auto bg-white rounded-xl border"><table className="w-full text-sm"><thead><tr className="text-left border-b"><th className="p-4">Filename</th><th className="p-4">Status</th><th className="p-4">Language</th><th className="p-4">Type</th><th className="p-4">Uploaded</th></tr></thead><tbody>{data.items.map(d => <tr key={d.id} className="border-b last:border-0"><td className="p-4"><Link className="text-blue-600 hover:underline" to={`/documents/${d.id}`}>{d.original_filename}</Link></td><td className="p-4"><span className="capitalize">{d.status.replace(/_/g, " ")}</span></td><td className="p-4">{d.detected_language ?? "—"}</td><td className="p-4">{d.document_type ?? "—"}</td><td className="p-4">{new Date(d.created_at).toLocaleString()}</td></tr>)}</tbody></table></div><div className="mt-4 flex gap-3"><button disabled={page <= 1} onClick={() => setPage(page - 1)} className="border px-3 py-1 rounded disabled:opacity-40">Previous</button><span className="py-1">Page {page}</span><button disabled={page * data.size >= data.total} onClick={() => setPage(page + 1)} className="border px-3 py-1 rounded disabled:opacity-40">Next</button></div></>}</div>; }

export { default as DocumentDetailPage } from "./DocumentDetailPage";

export function LandRecordsPage() { const [data,setData] = useState<PaginatedResponse<LandRecord> | null>(null); const [search,setSearch] = useState(""); const [error,setError] = useState(""); const load = () => landRecordsApi.list({search, page_size:20}).then(r=>setData(r.data)).catch(()=>setError("Failed to load land records")); useEffect(() => { void load(); }, []); return <div><h2 className="text-2xl font-bold mb-6">Land records</h2><div className="flex gap-2 mb-5"><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search village, district, survey or khasra" className="border rounded-lg px-3 py-2 w-full max-w-lg"/><button onClick={load} className="bg-blue-600 text-white px-4 rounded-lg">Search</button></div>{error&&<ErrorBox message={error}/>} {!data ? <p>Loading…</p> : data.items.length === 0 ? <Empty text="No land records found."/> : <div className="grid md:grid-cols-2 gap-4">{data.items.map(r=><Link key={r.id} to={`/land-records/${r.id}`} className={`${card} hover:border-blue-400`}><h3 className="font-semibold">{r.owners?.[0]?.landowner_name ?? "Unnamed owner"}</h3><p className="text-sm text-slate-500">Survey {r.survey_number ?? "—"} · {r.village ?? "—"}, {r.district ?? "—"}</p><p className="mt-3">{r.area ?? "—"} {r.area_unit ?? ""}</p></Link>)}</div>}</div>; }

export function LandRecordDetailPage() { const {id=""}=useParams(); const [record,setRecord]=useState<LandRecord|null>(null); const [error,setError]=useState(""); useEffect(()=>{landRecordsApi.get(id).then(r=>setRecord(r.data)).catch(()=>setError("Land record could not be loaded"))},[id]); if(error)return <ErrorBox message={error}/>; if(!record)return <p>Loading…</p>; const values: Record<string,unknown>={owner:record.owners?.map(o=>o.landowner_name).join(", "),guardian:"—",survey_number:record.survey_number,khasra_number:record.khasra_number,khata_number:record.khata_number,plot_number:record.plot_number,area:`${record.area??"—"} ${record.area_unit??""}`,village:record.village,tehsil:record.tehsil,district:record.district,state:record.state,ownership:record.owners?.map(o=>o.ownership_type).join(", "),mutation:record.mutations?.[0]?.mutation_number,registration:record.registrations?.[0]?.registration_number,confidence:record.overall_confidence==null?"—":`${(record.overall_confidence*100).toFixed(1)}%`}; return <div><Link to="/land-records" className="text-blue-600">← Land records</Link><h2 className="text-2xl font-bold mt-3 mb-6">Land record</h2><div className={`${card} grid sm:grid-cols-2 lg:grid-cols-3 gap-5`}>{Object.entries(values).map(([k,v])=><div key={k}><p className="text-xs uppercase text-slate-500">{k.replace(/_/g," ")}</p><p className="mt-1">{String(v??"—")}</p></div>)}</div><p className="mt-5 text-sm text-slate-500">Status: {record.status} · Source document: <Link className="text-blue-600" to={`/documents/${record.document_id}`}>{record.document_id}</Link></p></div>; }

export function SearchPage() { const [q,setQ]=useState(""); const [data,setData]=useState<PaginatedResponse<LandRecord>|null>(null); const [error,setError]=useState(""); const search=()=>landRecordsApi.list({search:q,page_size:20}).then(r=>setData(r.data)).catch(()=>setError("Search failed")); return <div><h2 className="text-2xl font-bold mb-6">Search land records</h2><div className="flex gap-2"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==="Enter"&&search()} placeholder="Owner, survey, khasra, khata, village or district" className="border rounded-lg px-3 py-2 w-full max-w-xl"/><button onClick={search} className="bg-blue-600 text-white px-4 rounded-lg">Search</button></div>{error&&<div className="mt-4"><ErrorBox message={error}/></div>}{data&&(data.items.length?<div className="mt-6 space-y-3">{data.items.map(r=><Link className="block bg-white border rounded-xl p-4 hover:border-blue-400" key={r.id} to={`/land-records/${r.id}`}>{r.survey_number??"No survey number"} · {r.village??""}, {r.district??""}</Link>)}</div>:<Empty text="No matching records."/> )}</div>; }

export function ReviewPage() { const [docs,setDocs]=useState<Document[]>([]); const [error,setError]=useState(""); useEffect(()=>{documentsApi.list({status:"review_needed",page_size:100}).then(r=>setDocs(r.data.items)).catch(()=>setError("Failed to load review queue"));},[]); return <div><h2 className="text-2xl font-bold mb-6">Review queue</h2>{error&&<ErrorBox message={error}/>} {!error&&!docs.length?<Empty text="No documents require review."/>:<div className="space-y-3">{docs.map(d=><Link key={d.id} to={`/review/${d.id}`} className={`${card} block hover:border-blue-400`}><p className="font-semibold">{d.original_filename}</p><p className="text-sm text-slate-500">{d.detected_language??"Language pending"} · {d.document_type??"Type pending"}</p></Link>)}</div>}</div>; }

export function ReviewDetailPage() { const {id=""}=useParams(); const [ext,setExt]=useState<ExtractionResult|null>(null); const [record,setRecord]=useState<LandRecord|null>(null); const [values,setValues]=useState<Record<string,string>>({}); const [message,setMessage]=useState(""); const [error,setError]=useState(""); useEffect(()=>{Promise.all([documentsApi.extraction(id),landRecordsApi.list({document_id:id,page_size:1})]).then(([e,r])=>{setExt(e.data);setRecord(r.data.items[0]??null);setValues(Object.fromEntries(Object.entries(e.data.mapped_record.fields).map(([k,v])=>[k,String(v??"")])))}).catch(()=>setError("Review data could not be loaded"));},[id]); if(error)return <ErrorBox message={error}/>; if(!ext||!record)return <p>Loading…</p>; const save=()=>documentsApi.review(id,record.id,values).then(()=>setMessage("Corrections saved and review completed.")).catch(()=>setError("Could not save review")); return <div><h2 className="text-2xl font-bold mb-6">Review extracted record</h2><div className={`${card} max-w-3xl space-y-4`}>{Object.entries(values).map(([k,v])=><label key={k} className="block"><span className="block text-sm text-slate-500 mb-1">{k.replace(/_/g," ")}</span><input value={v} onChange={e=>setValues({...values,[k]:e.target.value})} className="border rounded-lg px-3 py-2 w-full"/></label>)}<button onClick={save} className="bg-blue-600 text-white px-5 py-2 rounded-lg">Save corrections</button>{message&&<p className="text-green-700">{message}</p>}</div></div>; }

export function ReportsPage() { const download = async (format: "csv"|"json"|"xlsx") => { const response = await exportApi.download(format); const url = URL.createObjectURL(response.data); const a = document.createElement("a"); a.href = url; a.download = `land-records.${format}`; a.click(); URL.revokeObjectURL(url); }; return <div><h2 className="text-2xl font-bold mb-6">Reports and exports</h2><div className={`${card} max-w-xl`}><p className="text-slate-500 mb-4">Download current land-record data.</p><div className="flex gap-3"><button onClick={()=>void download("csv")} className="border px-4 py-2 rounded-lg">CSV</button><button onClick={()=>void download("json")} className="border px-4 py-2 rounded-lg">JSON</button><button onClick={()=>void download("xlsx")} className="border px-4 py-2 rounded-lg">Excel</button></div></div></div>; }
export function SettingsPage() { const { user } = useAuth(); return <div><h2 className="text-2xl font-bold mb-6">Settings</h2><div className={`${card} max-w-xl space-y-3`}><h3 className="font-semibold">Profile</h3><p>Name: {user?.full_name ?? "—"}</p><p>Email: {user?.email ?? "—"}</p><p>Role: {user?.is_superuser ? "ADMIN" : "USER"}</p><p className="text-sm text-slate-500">OCR languages: English, Hindi</p></div></div>; }
